---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: mar-25-eks
  region: us-east-1

nodeGroups:
  - name: ng-1
    instanceType: t2.medium
    desiredCapacity: 3
    volumeSize: 20

iam:
  withOIDC: true

addons:
  - name: aws-ebs-csi-driver
    wellKnownPolicies:
      ebsCSIController: true
