apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2025-05-18T20:56:43Z"
  generateName: backend-674b978c4f-
  labels:
    app: backend
    pod-template-hash: 674b978c4f
  name: backend-674b978c4f-99jls
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: backend-674b978c4f
    uid: 1934f4f7-c0fa-4296-beed-2d11e40a1d11
  resourceVersion: "99976"
  uid: 31d6bbfc-00c7-449a-803f-cf62062f16d6
spec:
  containers:
  - envFrom:
    - configMapRef:
        name: mysql-config
    image: azizul2go/two-tier-backend-image:latest
    imagePullPolicy: Always
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      failureThreshold: 3
      initialDelaySeconds: 20
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    name: backend
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /
        port: 5000
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 50Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-p8mpj
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: ip-192-168-26-66.ec2.internal
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-p8mpj
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-05-18T20:56:59Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2025-05-18T20:56:43Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-05-18T20:59:35Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-05-18T20:59:35Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-05-18T20:56:43Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://a6cb00756de3d11ee3f12e6ec8aef9151d377120fe2174de43c1b9ecdc594caf
    image: docker.io/azizul2go/two-tier-backend-image:latest
    imageID: docker.io/azizul2go/two-tier-backend-image@sha256:dc9fdbf8a3b2bfceec76602ac388413179944837dafaf0373f7010e03e37ef2e
    lastState:
      terminated:
        containerID: containerd://700687740747e9614f71a5c2b5f3bc4329f02d1e94149cd66e182f63010cd6ad
        exitCode: 137
        finishedAt: "2025-05-18T20:59:23Z"
        reason: Error
        startedAt: "2025-05-18T20:58:13Z"
    name: backend
    ready: true
    restartCount: 2
    started: true
    state:
      running:
        startedAt: "2025-05-18T20:59:23Z"
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-p8mpj
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 192.168.26.66
  hostIPs:
  - ip: 192.168.26.66
  phase: Running
  podIP: 192.168.15.223
  podIPs:
  - ip: 192.168.15.223
  qosClass: Burstable
  startTime: "2025-05-18T20:56:43Z"
