apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: frontend
    app.kubernetes.io/managed-by: Helm
  name: frontend-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: frontend
  type: NodePort
status:
  loadBalancer: {}
